-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.employer_users
(
    user_id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    web_site character varying(100) NOT NULL,
    phone_number character varying(10) NOT NULL,
    verify_email boolean NOT NULL
);

CREATE TABLE public.employer_users_validation
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_user_id integer NOT NULL,
    staff_user_id integer NOT NULL,
    is_valid boolean NOT NULL,
    date_of_validation date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseeker_users
(
    user_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    national_identity character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    verify_email boolean NOT NULL
);

CREATE TABLE public.roles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.staff_users
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(20) NOT NULL,
    created_date date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employer_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseeker_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.staff_users
    ADD FOREIGN KEY (role_id)
    REFERENCES public.roles (id)
    NOT VALID;


ALTER TABLE public.staff_users
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;